export const AUTH_OTP_VALIDATE_REQUEST = "AUTH_OTP_VALIDATE_REQUEST"
export const AUTH_OTP_VALIDATE_SUCCESS = "AUTH_OTP_VALIDATE_SUCCESS"
export const AUTH_OTP_VALIDATE_FAIL = "AUTH_OTP_VALIDATE_FAIL"
