export const AUTH_OTP_GENERATE_REQUEST = "AUTH_OTP_GENERATE_REQUEST"
export const AUTH_OTP_GENERATE_SUCCESS = "AUTH_OTP_GENERATE_SUCCESS"
export const AUTH_OTP_GENERATE_FAIL = "AUTH_OTP_GENERATE_FAIL"
